apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-deployments-petya
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: [ "deployments" ]
    verbs: [ get, list, update ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [get, list]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: petya
  namespace: default
subjects:
- kind: ServiceAccount
  name: petya
  namespace: default
roleRef:
  kind: Role
  name: list-deployments-petya
  apiGroup: rbac.authorization.k8s.io
