apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vasya
  namespace: default
subjects:
- kind: ServiceAccount
  name: vasya
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
